"D:\FlightGear 2018.3.2\bin\fgfs.exe" --fg-root="D:\FlightGear 2018.3.2\data" ^
--timeofday=dawn ^
--language=en ^
--prop:/systems/saloft=1 ^
--prop:/systems/bp=1 ^
--prop:/systems/noco=1 ^
--prop:/systems/nhtp=1 ^
--prop:/systems/nora=0 ^
--aircraft=FG-Platypus-180 ^
--in-air ^
--altitude=4000 ^
--heading=272 ^
--lon=-158.1631 ^
--lat=21.4417 ^
--prop:/controls/gear/brake-parking=0 ^
--prop:/controls/electrical/battery=true ^
--prop:/controls/electrical/alternator=true ^
--prop:/controls/switches/avionics-master=1 ^
--prop:/controls/engines/engine[0]/magnetos-switch=4 ^
--prop:/controls/engines/engine/mixture=1 ^
--prop:/controls/engines/engine/throttle=1 ^
--prop:/controls/engines/engine/running=true ^
--prop:/engines/engine[0]/rpm=2100 ^
--vc=105 ^
--geometry=800x600 ^
--enable-auto-coordination ^
--httpd=8080 ^
--disable-real-weather-fetch ^
--disable-ai-models ^
--disable-terrasync ^
--disable-ai-traffic ^
--disable-hud-3d ^
--visibility-miles=30 ^
--enable-freeze

