"D:\FlightGear 2018.3.2\bin\fgfs.exe" --fg-root="D:\FlightGear 2018.3.2\data" ^
--timeofday=morning ^
--wind=180:220@0:0 ^
--language=en ^
--prop:/systems/nora=0 ^
--nav1=263:109.3 ^
--prop:/systems/saloft=1 ^
--prop:/systems/bp=1 ^
--aircraft=WarriorII-180 ^
--in-air ^
--altitude=900 ^
--heading=258 ^
--airport=egkk ^
--runway=26L ^
--offset-distance=6 ^
--adf1=338 ^
--dme=nav1 ^
--prop:/controls/gear/brake-parking=0 ^
--prop:/controls/electrical/battery=true ^
--prop:/controls/electrical/alternator=true ^
--prop:/controls/switches/avionics-master=1 ^
--prop:/controls/engines/engine[0]/magnetos-switch=4 ^
--prop:/controls/engines/engine/mixture=1 ^
--prop:/controls/engines/engine/throttle=0.7 ^
--prop:/controls/engines/engine/running=true ^
--prop:/engines/engine[0]/rpm=2100 ^
--vc=115 ^
--geometry=800x600 ^
--enable-auto-coordination ^
--httpd=8080 ^
--disable-real-weather-fetch ^
--disable-ai-models ^
--disable-terrasync ^
--disable-ai-traffic ^
--disable-hud-3d ^
--visibility-miles=30 ^
--enable-freeze

